package td1;


/**
* td1/HorlogeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Horloge.idl
* lundi 7 février 2005 23 h 30 CET
*/

abstract public class HorlogeHelper
{
  private static String  _id = "IDL:td1/Horloge:1.0";

  public static void insert (org.omg.CORBA.Any a, td1.Horloge that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static td1.Horloge extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (td1.HorlogeHelper.id (), "Horloge");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static td1.Horloge read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_HorlogeStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, td1.Horloge value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static td1.Horloge narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof td1.Horloge)
      return (td1.Horloge)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      td1._HorlogeStub stub = new td1._HorlogeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static td1.Horloge unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof td1.Horloge)
      return (td1.Horloge)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      td1._HorlogeStub stub = new td1._HorlogeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
