package td1;


/**
* td1/Horloge.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Horloge.idl
* lundi 7 février 2005 23 h 30 CET
*/

public interface Horloge extends HorlogeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Horloge
