package td1;


/**
* td1/HorlogeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Horloge.idl
* lundi 7 février 2005 23 h 30 CET
*/

public interface HorlogeOperations 
{
  String localite ();
  String getTime ();
  void setHours (short h);
  void setMinutes (short m);
} // interface HorlogeOperations
